services:
  - type: web
    name: backend
    runtime: java
    plan: free
    rootDir: Hackathon     # 👈 points to the folder where pom.xml is
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
